version: "3.8"

services:
  prep-meet-backend:
    build: .
    container_name: prep-meet-backend-dev
    ports:
      - "4000:4000"
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
