version: "3.8"

services:
  prep-meet-backend:
    build: .
    container_name: prep-meet-backend-dev
    ports:
      - "4000:4000"
    command: npm run dev
    env_file:
      - .env
    volumes:
      - .:/app
      - /app/node_modules
    depends_on:
      - prep-meet-db

  prep-meet-db:
    image: postgres:15
    container_name: prep-meet-db-dev
    restart: always
    env_file:
      - .env
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
